# Generated by Django 4.2.5 on 2023-09-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_bills_ecs_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
