# Generated by Django 4.1.1 on 2023-09-26 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_customerdetail_transectiondetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customerdetail',
        ),
        migrations.DeleteModel(
            name='transectiondetail',
        ),
    ]
