# Generated by Django 4.1.1 on 2023-09-26 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_customerdetail_transectiondetail'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customerdetail',
            table='customers',
        ),
        migrations.AlterModelTable(
            name='transectiondetail',
            table='trans',
        ),
    ]
